package genesis

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"math/big"

	"github.com/xssnick/tonutils-go/address"
	"github.com/xssnick/tonutils-go/tlb"
	"github.com/xssnick/tonutils-go/ton"
	"github.com/xssnick/tonutils-go/tvm/cell"
)

const (
	rootShard                    = int64(-1 << 63)
	walletBalanceNano            = uint64(4_999_990_000_000_000_000)
	configBalanceNano            = uint64(10_000_000_000)
	validatorRegistryBalanceNano = uint64(100_000_000_000)
	walletV1CodeHex              = "b5ee9c7201010101004e000098ff0020dd2082014c97ba9730ed44d0d70b1fe0a4f260810200d71820d70b1fed44d0d31fd3ffd15112baf2a122f901541044f910f2a2f80001d31f31d307d4d101fb00a4c8cb1fcbffc9ed54"
	// Generated by crypto/smartcont/validator-registry.fif at C++ testnet 9a42919d.
	validatorRegistryCodeHex = "B5EE9C7241020E010002D0000114FF00F4A413F4BCF2C80B0102012002030202D0040502F6F2D31F21821032B85A9BBAE30221821034BDAA6CBA8E4331D4D1802EF833206EF2D38FD0D72C21B008B1F4F2BF810120D721D3000193D70BFF92306DE2206EB39721F90021BAC3009170E2F2E390F82AF900BDF2E391FB04F800E0018210CDB9D286BAF2E3848308D71820C8CEF91601D72C27DEC15814F2BFD31F080902012006070069401F833206E9130E0D020D74A9130E1D74C208010F4866FA5908E1601D32731D70BFFC840148307F44351218010F47C6FA5E85F03800012000E5081BA44C383435CB09D5C164E93CAFFD0134C0C870427CB8E3886B9B04B5C04C74600BBE0CC81BBCB4E3F435CB086C022C7D3CAFF4FFCC75C2C7DC08A0C1FD219BE964238A80A914C0EEFCB8E14075CB08206C89293CAFF4C0C870427CB8E3886B9B04B5C04C745444E0C1FD1F1BE97A17C16001FE31D1ED44D0D72C24DE391544F2BFF404D31FD1F834016F125CB9F2E386F8006D802001F002802201F002802401F002238307F4866FA5327091028E3D53058307F47C6FA53253248307F40E6FA13191329950278307F45B305066E202A4208014A9088E14C8CF926F1C8AA25270F40026CF0B1FC9ED54F80FDFE810345F04C80A02FAD307D30FD31FF404D1F834016F1215BAF2E38722C020917F9522C022C300E2917F9522C024C300E2F2E388F823A67821BCF2E389F823BCF2E38A01F833206EF2D38BD020D74AC200F2E38BD74C8010F40EF2E38BD32731D70BFFED44D0D72C24DE391544F2BFF404D31FD153218307F40E6FA19330706DE30DF82358BE0C0D011689CF1612F400CB1FC9ED540B00089BC722A8001CD72C22BBB37764F2BFD31FF404D100BAF2E38C541563F910F2E38DF800F823A678C8CF915DD9BBB221CF0B1F16F40052228307F443C8CF926F1C8AA25210F40024CF0B1FC9ED54F80F22F001C8CF915DD9BBB215CB1F12F40040138307F443C8CF926F1C8AA2F400CB1FC9ED54AF8120E1"
)

type builtGenesis struct {
	master            stateArtifact
	base              stateArtifact
	wallet            *address.Address
	validatorRegistry *address.Address
}

type stateArtifact struct {
	block ton.BlockIDExt
	root  *cell.Cell
	boc   []byte
}

func buildStates(spec validatedSpec, genesisTime uint32) (builtGenesis, error) {
	base, err := buildBaseState(spec.spec.GlobalID, genesisTime)
	if err != nil {
		return builtGenesis{}, err
	}

	walletState, wallet, err := buildWalletAccount(spec.validators[0].publicKey, genesisTime)
	if err != nil {
		return builtGenesis{}, err
	}

	var registryState *cell.Cell
	var registryAddress *address.Address
	if spec.spec.ValidatorRegistry != nil {
		registryState, registryAddress, err = buildValidatorRegistryAccount(genesisTime)
		if err != nil {
			return builtGenesis{}, err
		}
	}

	config, validatorHash, err := buildConfigRoot(
		spec,
		genesisTime,
		base.block.RootHash,
		base.block.FileHash,
		registryAddress,
	)
	if err != nil {
		return builtGenesis{}, err
	}
	accounts, err := tlb.NewShardAccountsAugDict()
	if err != nil {
		return builtGenesis{}, err
	}
	shardAccount, err := tlb.ToCell(&tlb.ShardAccount{
		Account:       walletState,
		LastTransHash: make([]byte, 32),
	})
	if err != nil {
		return builtGenesis{}, err
	}
	if err = accounts.SetIntKey(new(big.Int).SetBytes(walletAddress[:]), shardAccount); err != nil {
		return builtGenesis{}, fmt.Errorf("insert genesis wallet: %w", err)
	}
	configAccount, err := buildConfigAccount(config, genesisTime)
	if err != nil {
		return builtGenesis{}, err
	}
	configShardAccount, err := tlb.ToCell(&tlb.ShardAccount{
		Account:       configAccount,
		LastTransHash: make([]byte, 32),
	})
	if err != nil {
		return builtGenesis{}, err
	}
	if err = accounts.SetIntKey(new(big.Int).SetBytes(configAddress[:]), configShardAccount); err != nil {
		return builtGenesis{}, fmt.Errorf("insert genesis config account: %w", err)
	}
	if registryState != nil {
		registryShardAccount, err := tlb.ToCell(&tlb.ShardAccount{
			Account:       registryState,
			LastTransHash: make([]byte, 32),
		})
		if err != nil {
			return builtGenesis{}, err
		}
		if err = accounts.SetIntKey(new(big.Int).SetBytes(registryAddress.Data()), registryShardAccount); err != nil {
			return builtGenesis{}, fmt.Errorf("insert validator registry account: %w", err)
		}
	}

	totalBalance := walletBalanceNano + configBalanceNano
	if registryState != nil {
		totalBalance += validatorRegistryBalanceNano
	}
	stats, err := buildStateStats(totalBalance)
	if err != nil {
		return builtGenesis{}, err
	}
	queue, err := buildEmptyOutQueue()
	if err != nil {
		return builtGenesis{}, err
	}
	previous, err := cell.NewAugDict(32, keyMaxLTAugmentation{})
	if err != nil {
		return builtGenesis{}, err
	}
	info, err := tlb.ToCell(&tlb.McStateExtraBlockInfo{
		ValidatorInfo: tlb.ValidatorInfo{
			ValidatorListHashShort: validatorHash,
			CatchainSeqno:          0,
			NextCCUpdated:          true,
		},
		PrevBlocks:    &tlb.OldMcBlocksInfoAugDict{AugmentedDictionary: previous},
		AfterKeyBlock: true,
	})
	if err != nil {
		return builtGenesis{}, err
	}
	extra, err := tlb.ToCell(&tlb.McStateExtra{
		ShardHashes: cell.NewDict(32),
		ConfigParams: tlb.ConfigParams{
			ConfigAddr: configAddress[:],
			Config: struct {
				Params *cell.Dictionary `tlb:"dict inline 32"`
			}{Params: config},
		},
		Info:          info,
		GlobalBalance: currency(totalBalance),
	})
	if err != nil {
		return builtGenesis{}, err
	}

	masterRoot, err := tlb.ToCell(&tlb.ShardStateUnsplit{
		GlobalID:        spec.spec.GlobalID,
		ShardIdent:      tlb.ShardIdent{PrefixBits: 0, WorkchainID: -1, ShardPrefix: 0},
		GenUTime:        genesisTime,
		MinRefMCSeqno:   ^uint32(0),
		OutMsgQueueInfo: queue,
		Accounts: struct {
			ShardAccounts *tlb.ShardAccountsAugDict `tlb:"."`
		}{ShardAccounts: accounts},
		Stats:        stats,
		McStateExtra: extra,
	})
	if err != nil {
		return builtGenesis{}, fmt.Errorf("serialize masterchain zerostate: %w", err)
	}
	master := makeStateArtifact(-1, masterRoot)

	return builtGenesis{
		master:            master,
		base:              base,
		wallet:            wallet,
		validatorRegistry: registryAddress,
	}, nil
}

func buildBaseState(globalID int32, genesisTime uint32) (stateArtifact, error) {
	accounts, err := tlb.NewShardAccountsAugDict()
	if err != nil {
		return stateArtifact{}, err
	}
	stats, err := buildStateStats(0)
	if err != nil {
		return stateArtifact{}, err
	}
	queue, err := buildEmptyOutQueue()
	if err != nil {
		return stateArtifact{}, err
	}

	root, err := tlb.ToCell(&tlb.ShardStateUnsplit{
		GlobalID: globalID,
		// ShardID's top marker bit belongs to the external BlockIDExt encoding.
		// A root ShardIdent has an empty prefix, so its stored prefix is zero.
		ShardIdent:      tlb.ShardIdent{PrefixBits: 0, WorkchainID: 0, ShardPrefix: 0},
		GenUTime:        genesisTime,
		MinRefMCSeqno:   ^uint32(0),
		OutMsgQueueInfo: queue,
		Accounts: struct {
			ShardAccounts *tlb.ShardAccountsAugDict `tlb:"."`
		}{ShardAccounts: accounts},
		Stats: stats,
	})
	if err != nil {
		return stateArtifact{}, fmt.Errorf("serialize basechain zerostate: %w", err)
	}
	return makeStateArtifact(0, root), nil
}

func buildWalletAccount(publicKey [32]byte, genesisTime uint32) (*cell.Cell, *address.Address, error) {
	codeBOC, err := hex.DecodeString(walletV1CodeHex)
	if err != nil {
		return nil, nil, err
	}
	code, err := cell.FromBOC(codeBOC)
	if err != nil {
		return nil, nil, fmt.Errorf("parse embedded Wallet V1 code: %w", err)
	}
	data := cell.BeginCell().MustStoreUInt(0, 32).MustStoreSlice(publicKey[:], 256).EndCell()
	stateInit := &tlb.StateInit{Code: code, Data: data, Lib: cell.NewDict(256)}
	storage := tlb.AccountStorage{
		Status:          tlb.AccountStatusActive,
		Balance:         nanoCoins(walletBalanceNano),
		ExtraCurrencies: cell.NewDict(32),
		StateInit:       stateInit,
	}
	storageCell, err := storage.ToCell()
	if err != nil {
		return nil, nil, err
	}
	cells, bits := cellTreeSize(storageCell)
	wallet := address.NewAddress(0, 0xff, walletAddress[:]).Bounce(true).Testnet(true)
	account, err := (tlb.AccountState{
		IsValid: true,
		Address: wallet,
		StorageInfo: tlb.StorageInfo{
			StorageUsed:  tlb.StorageUsed{CellsUsed: new(big.Int).SetUint64(cells), BitsUsed: new(big.Int).SetUint64(bits)},
			StorageExtra: tlb.StorageExtraNone{},
			LastPaid:     genesisTime,
		},
		AccountStorage: storage,
	}).ToCell()
	if err != nil {
		return nil, nil, err
	}
	return account, wallet, nil
}

func buildConfigAccount(config *cell.Dictionary, genesisTime uint32) (*cell.Cell, error) {
	data := cell.BeginCell().MustStoreRef(config.AsCell()).EndCell()
	storage := tlb.AccountStorage{
		Status:          tlb.AccountStatusActive,
		Balance:         nanoCoins(configBalanceNano),
		ExtraCurrencies: cell.NewDict(32),
		StateInit:       &tlb.StateInit{Data: data, Lib: cell.NewDict(256)},
	}
	storageCell, err := storage.ToCell()
	if err != nil {
		return nil, err
	}
	cells, bits := cellTreeSize(storageCell)

	return (tlb.AccountState{
		IsValid: true,
		Address: address.NewAddress(0, 0xff, configAddress[:]),
		StorageInfo: tlb.StorageInfo{
			StorageUsed:  tlb.StorageUsed{CellsUsed: new(big.Int).SetUint64(cells), BitsUsed: new(big.Int).SetUint64(bits)},
			StorageExtra: tlb.StorageExtraNone{},
			LastPaid:     genesisTime,
		},
		AccountStorage: storage,
	}).ToCell()
}

func buildValidatorRegistryAccount(genesisTime uint32) (*cell.Cell, *address.Address, error) {
	codeBOC, err := hex.DecodeString(validatorRegistryCodeHex)
	if err != nil {
		return nil, nil, err
	}
	code, err := cell.FromBOC(codeBOC)
	if err != nil {
		return nil, nil, fmt.Errorf("parse embedded validator registry code: %w", err)
	}
	data := cell.BeginCell().
		MustStoreUInt(0x9bc722a8, 32).
		MustStoreDict(cell.NewDict(256)).
		MustStoreUInt(0, 32).
		EndCell()
	stateInit := &tlb.StateInit{Code: code, Data: data, Lib: cell.NewDict(256)}
	registryAddress := stateInit.CalcAddress(-1)
	storage := tlb.AccountStorage{
		Status:          tlb.AccountStatusActive,
		Balance:         nanoCoins(validatorRegistryBalanceNano),
		ExtraCurrencies: cell.NewDict(32),
		StateInit:       stateInit,
	}
	storageCell, err := storage.ToCell()
	if err != nil {
		return nil, nil, err
	}
	cells, bits := cellTreeSize(storageCell)
	account, err := (tlb.AccountState{
		IsValid: true,
		Address: registryAddress,
		StorageInfo: tlb.StorageInfo{
			StorageUsed:  tlb.StorageUsed{CellsUsed: new(big.Int).SetUint64(cells), BitsUsed: new(big.Int).SetUint64(bits)},
			StorageExtra: tlb.StorageExtraNone{},
			LastPaid:     genesisTime,
		},
		AccountStorage: storage,
	}).ToCell()
	if err != nil {
		return nil, nil, err
	}
	return account, registryAddress, nil
}

func buildEmptyOutQueue() (*cell.Cell, error) {
	out, err := tlb.NewOutMsgQueueAugDict()
	if err != nil {
		return nil, err
	}
	return (tlb.OutMsgQueueInfo{OutQueue: out, ProcInfo: cell.NewDict(96)}).ToCell()
}

func buildStateStats(balance uint64) (*cell.Cell, error) {
	return (tlb.ShardStateStats{
		TotalBalance:       currency(balance),
		TotalValidatorFees: currency(0),
		Libraries:          cell.NewDict(256),
	}).ToCell()
}

func currency(coins uint64) tlb.CurrencyCollection {
	return tlb.CurrencyCollection{Coins: nanoCoins(coins), ExtraCurrencies: cell.NewDict(32)}
}

func makeStateArtifact(workchain int32, root *cell.Cell) stateArtifact {
	boc := root.ToBOCWithOptions(cell.BOCSerializeOptions{WithCRC32C: false})
	fileHash := sha256.Sum256(boc)
	return stateArtifact{
		block: ton.BlockIDExt{
			Workchain: workchain,
			Shard:     rootShard,
			SeqNo:     0,
			RootHash:  bytes.Clone(root.Hash()),
			FileHash:  bytes.Clone(fileHash[:]),
		},
		root: root,
		boc:  boc,
	}
}

func cellTreeSize(root *cell.Cell) (uint64, uint64) {
	seen := make(map[cell.Hash]struct{})
	stack := []*cell.Cell{root}
	var cells uint64
	var bits uint64
	for len(stack) > 0 {
		current := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		hash := current.HashKey()
		if _, exists := seen[hash]; exists {
			continue
		}
		seen[hash] = struct{}{}
		cells++
		bits += uint64(current.BitsSize())
		slice := current.MustBeginParse()
		for slice.RefsNum() > 0 {
			stack = append(stack, slice.MustLoadRef().MustToCell())
		}
	}
	return cells, bits
}

type keyMaxLTAugmentation struct{}

func (keyMaxLTAugmentation) SkipExtra(loader *cell.Slice) error {
	return loader.SkipBits(65)
}

func (keyMaxLTAugmentation) EmptyExtra(dst *cell.Builder) error {
	return dst.StoreUInt(0, 65)
}

func (keyMaxLTAugmentation) LeafExtra(*cell.Slice, *cell.Builder) error {
	return fmt.Errorf("old masterchain blocks augmentation is empty-only")
}

func (keyMaxLTAugmentation) CombineExtra(*cell.Slice, *cell.Slice, *cell.Builder) error {
	return fmt.Errorf("old masterchain blocks augmentation is empty-only")
}
